import { createContext, useContext, useState, type ReactNode } from 'react'

export type Language = 'sw' | 'en'

const T: Record<Language, Record<string, string>> = {
  sw: {
    login:'Ingia', logout:'Toka', username:'Jina la mtumiaji', password:'Neno la siri',
    logging_in:'Inaingia...', welcome_back:'Karibu tena', login_subtitle:'Ingia kwa akaunti yako',
    invalid_credentials:'Jina au neno la siri si sahihi', account_disabled:'Akaunti imezuiwa',
    accounts_by_admin:'Akaunti zinaundwa na msimamizi peke yake',
    dashboard:'Dashibodi', clients:'Wateja', routers:'Routers', packages:'Vifurushi',
    vouchers:'Vouchers', payments:'Malipo', devices:'Vifaa GSM', mikrotik_mgmt:'Simamia MikroTik',
    summary:'Muhtasari wa Leo', total_clients:'Wateja Wote', online_routers:'Zipo Online',
    today_revenue:'Mapato Leo', today_commission:'Commission Leo', vouchers_today:'Vouchers Leo',
    active_devices:'Vifaa Active', my_balance:'Bakaa Yangu', pending_jobs:'Kazi Zinazosubiri',
    system_status:'Hali ya Mfumo', recent_vouchers:'Vouchers za Hivi Karibuni',
    total_routers:'Routers Zote', month_revenue:'Mapato ya Mwezi', today:'Leo',
    add_client:'Ongeza Mteja', business_name:'Jina la Biashara', reference_prefix:'Prefix',
    commission_rate:'Commission (%)', balance:'Bakaa', status:'Hali', active:'Inafanya Kazi',
    inactive:'Imezuiwa', add_balance:'Ongeza Bakaa', current_balance:'Bakaa ya Sasa',
    amount:'Kiasi', save:'Hifadhi', cancel:'Ghairi', create_client:'Unda Mteja',
    auto_generated:'Itatengenezwa automatically', email:'Barua pepe', phone:'Simu',
    activate:'Washa Akaunti', deactivate:'Zima Akaunti', change_password:'Badilisha Password',
    new_password:'Password Mpya', delete_client:'Futa Mteja', confirm_delete:'Thibitisha Kufuta',
    add_router:'Ongeza Router', router_name:'Jina la Router', host:'Host (VPN IP)',
    api_port:'API Port', api_username:'Username ya API', api_password:'Password ya API',
    hotspot_interface:'Interface ya Hotspot', test_connection:'Jaribu Kuunganika',
    sync_packages:'Sync Vifurushi', online:'Online', offline:'Offline', last_seen:'Mwisho Kuonekana',
    never:'Haijawahi', testing:'Inajaribu...', edit_router:'Hariri Router', delete_router:'Futa Router',
    vpn_hint:'Weka VPN IP ya MikroTik (mfano: 10.66.66.2) baada ya kuunganisha WireGuard',
    router_status:'Hali ya Router', interfaces:'Interfaces', ip_addresses:'IP Addresses',
    hotspot_users:'Hotspot Users', active_sessions:'Sessions Active', hotspot_profiles:'Profiles',
    firewall:'Firewall', logs:'Logs', dns:'DNS', bandwidth:'Bandwidth',
    restart_router:'Restart Router', disconnect_session:'Kata Connection',
    delete_user:'Futa User', add_user:'Ongeza User',
    cpu_load:'CPU Load', memory:'Kumbukumbu', uptime:'Muda wa Kufanya Kazi',
    no_sessions:'Hakuna watumiaji waliounganishwa sasa',
    restart_confirm:'Una uhakika unataka kuanza router upya? Wateja wote watakatika.',
    add_package:'Ongeza Kifurushi', package_name:'Jina', price:'Bei (TZS)',
    duration_minutes:'Muda (dakika)', speed_down:'Download (Mbps)', speed_up:'Upload (Mbps)',
    mikrotik_profile:'MikroTik Profile', shared_users:'Shared Users', save_package:'Hifadhi',
    no_packages:'Hakuna vifurushi. Ongeza cha kwanza!',
    code:'Code', customer_phone:'Simu ya Mteja', all:'Zote', used:'Zimetumika', expired:'Zimeisha',
    no_vouchers:'Hakuna vouchers bado',
    no_payments:'Hakuna malipo bado', total_payments:'Jumla ya Malipo',
    my_revenue:'Mapato Yangu', grand_total:'Jumla Kubwa',
    add_device:'Ongeza Device', device_name:'Jina la Device', device_id:'Device ID',
    phone_number:'Namba ya SIM', description:'Maelezo', save_device:'Hifadhi Device',
    no_devices_admin:'Hakuna vifaa. Ongeza A7670E ya kwanza!',
    edit_device:'Hariri Device', device_id_hint:'Lazima iwe sawa na A7670E inayotuma',
    lipa_namba:'Namba za Kulipa', pay_instruction:'Wateja waweke namba ya lipa na reference yako',
    reference:'Reference yako', lipa_number:'Namba ya Lipa', no_devices:'Hakuna GSM devices',
    network:'Mtandao',
    loading:'Inapakia...', no_data:'Hakuna data', error:'Hitilafu', success:'Imefanikiwa',
    delete:'Futa', edit:'Hariri', search:'Tafuta', from_date:'Tangu', to_date:'Hadi',
    actions:'Vitendo', super_admin:'Super Admin', client:'Client', created_at:'Iliundwa',
    app_name:'NetSafi', app_tagline:'Mfumo wa Hotspot Tanzania', refresh:'Sasisha',
    manage:'Simamia',
    zipo_online_sasa: 'Zipo online sasa',
    gsm_devices: 'GSM Devices',
    vouchers_this_week: 'Vouchers za Wiki Hii',
    prefix: 'Prefix',
    commission: 'Commission',
    no_clients_yet: 'Hakuna wateja bado',
    all_routers_subtitle: 'Routers za wateja wote',
    all_payments_subtitle: 'Historia ya malipo ya wateja wote',
    all_vouchers_subtitle: 'Vouchers za wateja wote',
    total_commission: 'Commission Yote',
    no_routers: 'Hakuna routers',
    payment_instructions: 'Maagizo ya Malipo',
    how_customers_pay: 'Jinsi Wateja Wanavyolipa',
    pay_step_1: 'Mteja achague package — kila moja ina bei maalum.',
    pay_step_2: 'Bei tayari imejumuisha nambari yako',
    pay_step_2_suffix: '— alipe kiasi kamili bila mabadiliko.',
    pay_step_3_prefix: 'Mfano: Package TZS 500 → mteja alipe',
    pay_step_3_to: 'kwenda Lipa Namba',
    pay_step_4: 'Mfumo utatuma voucher kwa mteja moja kwa moja kupitia SMS.',
    automatic: 'Otomatiki',
    your_number: 'Nambari Yako',
    bakaa: 'Bakaa',
    bakaa_ya_sasa: 'Bakaa ya Sasa',
    by_hour: 'Kwa saa',
    welcome_client: 'Habari',
    business_summary_today: 'Muhtasari wa shughuli zako za biashara leo',
    payments_today: 'Malipo Leo',
    vouchers_today_chart: 'Vouchers za Leo',
    no_vouchers_today: 'Hakuna vouchers zilizotolewa leo',

    // ── Voucher Management Page ──
    voucher_page_subtitle: 'Simamia, unda, na chapisha vouchers',
    theme_blue: 'Bluu', theme_green: 'Kijani', theme_purple: 'Zambarau', theme_red: 'Nyekundu',
    theme_orange: 'Chungwa', theme_teal: 'Teal', theme_black: 'Nyeusi', theme_gold: 'Dhahabu',
    code_settings_title: 'Mipangilio ya Code',
    char_type_label: 'Aina ya Herufi',
    type_mixed: 'Mchanganyiko', type_letters: 'Herufi Tu', type_numbers: 'Namba Tu',
    char_case_label: 'Ukubwa wa Herufi',
    case_upper: 'KUBWA (ABC)', case_lower: 'Ndogo (abc)',
    char_count_label: 'Idadi ya Herufi',
    preview_label: 'Preview',
    tab_voucher_list: 'Lista ya Vouchers', tab_voucher_manual: 'Unda Moja', tab_voucher_batch: 'Unda Batch',
    th_package: 'Package', print: 'Print',
    print_selected_prefix: 'Chapisha',
    deselect_all: 'Futa Chaguo', select_all: 'Chagua Zote',
    create_manual_title: 'Unda Voucher Moja Kwa Moja',
    router_online_required: 'Router (lazima iwe online) *',
    choose_router: 'Chagua Router',
    customer_phone_optional: 'Simu ya Mteja (optional)',
    custom_code_label: 'Code ya Maalum (acha tupu = random)',
    preview_code_label: 'Preview code',
    voucher_color_label: 'Rangi ya Voucher (Print)',
    creating: 'Inaunda...',
    create_voucher_btn: 'Unda Voucher',
    preview_voucher_label: 'Preview ya Voucher',
    choose_router_profile_prompt: 'Chagua router na profile',
    create_batch_title: 'Unda Vouchers Nyingi (Batch)',
    quantity_label: 'Idadi ya Vouchers (1–200) *',
    vouchers_color_label: 'Rangi ya Vouchers (Print)',
    creating_on_mikrotik: 'Inaunda vouchers kwenye MikroTik...',
    create_batch_btn_prefix: 'Unda Vouchers',
    vouchers_created_prefix: 'Vouchers', vouchers_created_suffix: 'Zimeundwa!',
    print_all: 'Chapisha Zote',
    hotspot_profile_star: 'Hotspot Profile *',
    choose_router_first: 'Chagua router kwanza...',
    loading_profiles_mikrotik: 'Inapakia profiles kutoka MikroTik...',
    profiles_count_prefix: 'Profiles', profiles_count_suffix: 'kutoka MikroTik',
    print_modal_title_prefix: 'Chapisha Vouchers',
    color_label: 'Rangi',
    close: 'Funga', print_now: 'Chapisha Sasa',
    print_question: 'Unataka kuzipiga print?',
    duration_days_prefix: 'Siku', duration_hours_prefix: 'Saa',
    alert_select_router_profile: 'Chagua router na profile',
    alert_voucher_created_prefix: 'Voucher', alert_voucher_created_suffix: 'imeundwa!',
    alert_create_failed: 'Imeshindwa — angalia router ipo online',
    alert_quantity_range: 'Quantity lazima iwe kati ya 1 na 200',
    alert_batch_partial_ok: 'imefanikiwa', alert_batch_partial_failed: 'imeshindwa',
    alert_batch_success_prefix: 'Vouchers', alert_batch_success_suffix: 'zimeundwa!',
    alert_batch_router_failed: 'Imeshindwa kuwasiliana na router',

    // ── MikroTik Manager Page ──
    mt_no_permission_title: 'Huna ruhusa ya kufikia MikroTik Manager',
    mt_no_permission_title_short: 'Huna ruhusa ya MikroTik Manager',
    mt_no_permission_contact: 'Wasiliana na admin wako kukupa ruhusa.',
    mt_no_permission_contact_short: 'Wasiliana na admin kukupa ruhusa.',
    mt_terminal_banner: 'Tekeleza commands moja kwa moja kwenye router yako. Commands zinatumwa salama kupitia API.',
    mt_quick_commands: 'Quick Commands',
    mt_keyboard_label: 'Keyboard:',
    mt_history: 'history', mt_run_hint: 'run', mt_clear_hint: 'clear',
    mt_clear: 'Clear', mt_executing: 'Inatekeleza...', mt_waiting_response: 'Inasubiri jibu kutoka MikroTik...',
    mt_command_placeholder: 'Andika command... (mfano: /ip/address/print)',
    mt_run_btn: 'Run',
    mt_hotspot_servers: 'Hotspot Servers', mt_no_servers: 'Hakuna hotspot servers',
    mt_server_profiles: 'Server Profiles',
    mt_profile_tip: 'Bonyeza profile yoyote kuona na kuhariri maelezo yake (General, Scripts)',
    mt_no_profiles: 'Hakuna server profiles',
    mt_edit_profile: 'Hariri Profile',
    th_name: 'Name', th_rate_limit: 'Rate Limit', th_session_timeout: 'Session Timeout',
    th_shared_users: 'Shared Users', th_on_login_script: 'On Login Script', th_status: 'Status',
    mt_ipo: 'Ipo', mt_hakuna: 'Hakuna',
    mt_users_tip: 'Bonyeza jina la user kuona na kuhariri maelezo yake',
    mt_search_users_placeholder: 'Tafuta kwa username, comment au profile...',
    mt_selected_count_suffix: 'zimechaguliwa',
    mt_delete_selected: 'Futa zilizochaguliwa', mt_deselect: 'Ondoa uchaguzi',
    mt_select_all_filtered_prefix: 'Chagua wote', mt_deselect_all_filtered: 'Ondoa uchaguzi wote',
    mt_no_users_match_prefix: 'Hakuna user inayofanana na', mt_no_users: 'Hakuna users',
    th_profile: 'Profile', th_limit_uptime: 'Limit Uptime', th_uptime_hali: 'Uptime / Hali',
    th_comment: 'Comment', th_unlimited: 'unlimited',
    mt_never_used: 'Haijatumika', mt_login_label: 'Login', mt_last_label: 'Mwisho', mt_nje: 'Nje',
    mt_edit_user: 'Hariri User',
    mt_no_active_sessions: 'Hakuna active sessions',
    th_user: 'User', th_mac: 'MAC Address', th_ip: 'IP Address', th_tx: 'TX Bytes', th_rx: 'RX Bytes', th_server: 'Server',
    mt_disconnect: 'Kata Connection',
    mt_disconnect_confirm_title: 'Disconnect Session', mt_disconnect_confirm_msg: 'Una uhakika unataka kukata connection hii?',
    mt_hosts_title: 'Hosts', th_hostname: 'Hostname', th_bridge: 'Bridge',
    mt_authorized: 'authorized', mt_unauthorized: 'unauthorized', mt_no_hosts: 'Hakuna hosts',
    mt_ip_bindings: 'IP Bindings', mt_add_binding: 'Add Binding', mt_no_bindings: 'Hakuna IP Bindings',
    mt_binding_regular: 'Regular — mtumiaji wa kawaida', mt_binding_bypassed: 'Bypassed — anaruhusiwa bila login',
    mt_binding_blocked: 'Blocked — amezuiwa kabisa', mt_remove_binding: 'Futa Binding',
    mt_remove_binding_title: 'Remove IP Binding', mt_remove_binding_msg: 'Una uhakika unataka kufuta IP Binding hii?',
    mt_walled_garden: 'Walled Garden', mt_add_entry: 'Add Entry',
    mt_wg_tip: 'Tovuti zinazoweza kufikiwa bila login (HTTP)', mt_no_wg: 'Hakuna Walled Garden entries',
    mt_remove_entry: 'Futa Entry', mt_remove_wg_title: 'Remove Walled Garden', mt_remove_wg_msg: 'Una uhakika unataka kufuta entry hii?',
    mt_walled_garden_ip: 'Walled Garden IP List', mt_add_ip: 'Add IP',
    mt_wgip_tip: 'IP addresses zinazoweza kufikiwa bila login (HTTPS/IP direct)', mt_no_wgip: 'Hakuna Walled Garden IP entries',
    mt_remove_ip: 'Futa IP', mt_remove_wgip_title: 'Remove Walled Garden IP', mt_remove_wgip_msg: 'Una uhakika unataka kufuta IP hii?',
    mt_cookies: 'Cookies', mt_clear_all: 'Clear All',
    mt_cookies_tip: 'Login cookies — ruhusu mtumiaji kuingia bila password tena',
    mt_no_cookies: 'Hakuna cookies', mt_remove_cookie: 'Futa Cookie',
    mt_remove_cookie_title: 'Remove Cookie', mt_remove_cookie_msg: 'Futa cookie hii? Mtumiaji atalazimika kuingia tena.',
    mt_clear_cookies_title: 'Clear All Cookies', mt_clear_cookies_msg: 'Futa cookies ZOTE? Watumiaji wote watalazimika kuingia tena.',
    th_expires_at: 'Expires At',
    mt_scheduler: 'Scheduler', mt_add_schedule: 'Add Schedule',
    mt_scheduler_tip: 'Bonyeza scheduler kuona na kuhariri script yake kamili', mt_no_schedulers: 'Hakuna schedulers',
    th_start_date: 'Start Date', th_start_time: 'Start Time', th_interval: 'Interval',
    th_run_count: 'Run Count', th_next_run: 'Next Run', mt_once: 'once',
    mt_edit_scheduler: 'Hariri Scheduler', mt_enable: 'Washa (Enable)', mt_disable: 'Zima (Disable)',
    mt_delete_scheduler: 'Futa Scheduler', mt_delete_scheduler_title: 'Futa Scheduler',
    mt_delete_scheduler_msg: 'Futa scheduler hii? Script haitatekelezwa tena.',
    mt_bulk_delete_title: 'Futa Users Walizochaguliwa',
    mt_bulk_delete_msg_prefix: 'Una uhakika unataka kufuta', mt_bulk_delete_msg_suffix: 'user(s)? Hatua hii haiwezi kurudishwa!',
    mt_deleting: 'Inafuta...',
    mt_add_user_title: 'Add User', mt_username_star: 'Username *', mt_password_default: 'Password (default = username)',
    mt_leave_blank: 'Acha tupu', mt_profile_label: 'Profile', mt_loading_short: 'Inapakia...',
    mt_comment_optional: 'Comment (optional)', mt_customer_name_hint: 'Jina la mteja',
    mt_add_binding_title: 'Add IP Binding', mt_mac_star: 'MAC Address *', mt_ip_optional: 'IP Address (optional)',
    mt_type_label: 'Type', mt_notes_hint: 'Maelezo',
    mt_add_wg_title: 'Add Walled Garden Entry', mt_dst_host_star: 'Dst Host *',
    mt_action_label: 'Action', mt_allow_desc: 'Allow — ruhusu bila login', mt_deny_desc: 'Deny — zuia',
    mt_add_wgip_title: 'Add Walled Garden IP', mt_dst_address_star: 'Dst Address *',
    mt_accept_desc: 'Accept — ruhusu', mt_drop_desc: 'Drop — zuia',
    mt_add_scheduler_title: 'Add Scheduler', mt_edit_scheduler_prefix: 'Edit',
    mt_scheduler_name_star: 'Name *', mt_start_date_hint: 'Format: jan/01/1970', mt_start_time_hint: 'Format: HH:MM:SS',
    mt_interval_hint: 'Interval (00:00:00 = mara moja tu)',
    mt_policy_label: 'Policy', mt_on_event_star: 'On Event (Script) *',
    mt_examples_label: 'Mifano:', mt_examples_label_full: 'Mifano ya haraka:',
    mt_scheduler_comment_hint: 'Maelezo ya scheduler', mt_initial_status: 'Hali ya Awali',
    mt_update_btn: 'Sasisha', mt_add_scheduler_btn: 'Ongeza Scheduler',
    mt_live_label: 'Live',
    mt_permissions_title: 'MikroTik Permissions', mt_select_all_features: 'Chagua Zote', mt_clear_all_features: 'Futa Zote',
    mt_features_selected_suffix: 'features zimechaguliwa', mt_saving: 'Inahifadhi...',
    mt_save_failed: 'Imeshindwa kuhifadhi permissions',
    mt_mikrotik_by_client_subtitle: 'IP → Hotspot (kama Winbox)',
    mt_mikrotik_by_admin_subtitle: 'Simamia routers zote za clients',
    mt_back: 'Rudi', mt_no_routers_short: 'Hakuna routers',
    mt_feature_desc_servers: 'Ona hotspot servers', mt_feature_desc_server_profiles: 'Ona server profiles',
    mt_feature_desc_users: 'Simamia hotspot users', mt_feature_desc_active: 'Ona na kata sessions',
    mt_feature_desc_hosts: 'Vifaa vilivyounganika', mt_feature_desc_ip_bindings: 'Simamia IP bindings',
    mt_feature_desc_walled_garden: 'Tovuti bila login (HTTP)', mt_feature_desc_walled_garden_ip: 'IPs bila login (HTTPS)',
    mt_feature_desc_cookies: 'Simamia login cookies', mt_feature_desc_scheduler: 'Scripts za wakati maalum',
    mt_feature_desc_terminal: 'Run commands moja kwa moja',
    mt_funga: 'Funga', mt_hifadhi: 'Hifadhi',

    // ── Generic UI (confirm dialogs, forms, save states) ──
    confirm: 'Thibitisha',
    saving_label: 'Inahifadhi...',
    fill_required: 'Tafadhali jaza taarifa zote zinazohitajika',
    updated_success: 'imesasishwa',
    created_success: 'imeundwa',
    deleted_success: 'imefutwa',

    // ── Client Packages page ──
    manage_packages_subtitle: 'Simamia vifurushi vyako vya intaneti',
    sync_all: 'Sync Zote',
    sync: 'Sync',
    sync_all_success: 'Packages zote zime-sync kwa MikroTik',
    sync_failed: 'Sync imeshindwa',
    customers: 'Wateja',
    customers_pay: 'Wateja watalipa',
    base_price_note: 'Bei inayoonekana kwenye kadi ni bei ya msingi.',
    customers_will_pay: 'Wateja wako watalipa',
    example_label: 'Mfano',
    duration_of_package: 'Muda wa Package',
    hours_unit: 'Masaa',
    days_unit: 'Siku',
    minutes_unit: 'dakika',
    confirm_delete_package_prefix: 'Futa package',

    // ── Withdraw / Withdrawal Requests ──
    withdraw: 'Toa Fedha',
    withdraw_page_subtitle: 'Omba kutoa fedha kutoka kwenye bakaa yako',
    request_withdrawal: 'Omba Kutoa Fedha',
    account_name: 'Jina la Mtoaji',
    withdrawal_history: 'Historia ya Maombi',
    no_withdrawals: 'Hakuna maombi bado',
    withdrawal_requested_success: 'Ombi lako limetumwa — linasubiri idhini ya admin',
    withdrawal_requests: 'Maombi ya Kutoa Fedha',
    withdrawal_requests_subtitle: 'Simamia maombi ya wateja ya kutoa fedha',
    approve: 'Kubali',
    reject: 'Kataa',
    pending_status: 'Inasubiri',
    approved_status: 'Imekubaliwa',
    rejected_status: 'Imekataliwa',
    approve_withdrawal_title: 'Kubali Ombi la Kutoa Fedha',
    approve_withdrawal_message_prefix: 'Una uhakika unataka kukubali ombi la',
    reject_withdrawal_title: 'Kataa Ombi la Kutoa Fedha',
    reject_reason_prompt: 'Sababu ya kukataa (hiari)',
    reject_reason_placeholder: 'Mfano: Namba ya lipa siyo sahihi',
    withdrawal_approved_success: 'Ombi limekubaliwa na balance imepunguzwa',
    withdrawal_rejected_success: 'Ombi limekataliwa',

    // ── MikroTik Manager — small set of keys missing for full coverage ──
    view: 'Angalia',
    mt_view_tooltip: 'Angalia tu (View)',
    mt_edit_tooltip: 'Hariri (Edit)',
    mt_tab_general: 'General',
    mt_tab_scripts: 'Scripts',
    mt_tab_script: 'Script',
    mt_tab_statistics: 'Statistics',
    mt_profile_modal_title: 'Hotspot User Profile',
    mt_user_modal_title: 'Hotspot User',
    mt_cannot_change: 'haiwezi kubadilika',
    mt_hidden: 'hidden',
    mt_yes: 'Ndiyo',
    mt_no: 'Hapana',
    mt_ok: 'Sawa',
    mt_apply: 'Tumia',
    mt_on_login: 'On Login',
    mt_on_logout: 'On Logout',
    mt_no_script: 'Hakuna script',
    mt_no_stats: 'Hakuna statistics — user hajawahi kuingia',
    mt_no_results: 'hakuna matokeo',
    mt_empty_list: 'orodha tupu',
    mt_command_failed: 'Command imeshindwa',
    mt_connection_error: 'Hitilafu ya muunganiko',
    mt_results_label: 'Matokeo',
    mt_items_label: 'item(s)',
    mt_term_ready: 'MikroTik Terminal — tayari kutumia',
    mt_term_intro: 'Tumia quick commands au andika command mwenyewe hapa chini.',
    mt_terminal_cleared: 'Terminal imefutwa.',
    mt_terminal_cleared_ready: 'Terminal imesafishwa. Tayari kutumia.',
    mt_clear_screen_tooltip: 'Futa skrini ya terminal',
    mt_save_generic_failed: 'Imeshindwa kuhifadhi',
    mt_session_disconnected: 'Session imekatwa',
    mt_action_irreversible: 'Hatua hii haiwezi kurudishwa!',
    mt_confirm_delete_user_msg_prefix: 'Futa user',
    mt_bulk_failed_note: ', imeshindwa kufuta',
    mt_any: 'yoyote',
    mt_ph_new_password: 'Weka password mpya',
    mt_ph_bytes_unlimited: 'bytes (0 = unlimited)',
    mt_opt_active_desc: 'Active — mtumiaji anaweza kuingia',
    mt_opt_disabled_desc: 'Disabled — mtumiaji amezuiwa',
    mt_opt_enabled_desc: 'Enabled — inafanya kazi',
    mt_opt_disabled_desc2: 'Disabled — imesimamishwa',
    mt_lbl_idle_timeout: 'Idle Timeout',
    mt_lbl_keepalive_timeout: 'Keepalive Timeout',
    mt_lbl_dns_name: 'DNS Name',
    mt_lbl_html_directory: 'HTML Directory',
    mt_lbl_http_cookie_lifetime: 'HTTP Cookie Lifetime',
    mt_lbl_status_autorefresh: 'Status Auto-Refresh',
    mt_lbl_address_pool: 'Address Pool',
    mt_lbl_mac_cookie_timeout: 'MAC Cookie Timeout',
    mt_lbl_transparent_proxy: 'Transparent Proxy',
    mt_lbl_limit_bytes_in: 'Limit Bytes In',
    mt_lbl_limit_bytes_out: 'Limit Bytes Out',
    mt_lbl_limit_bytes_total: 'Limit Bytes Total',
    mt_lbl_disabled_field: 'Disabled',
    mt_lbl_bytes_in: 'Bytes In',
    mt_lbl_bytes_out: 'Bytes Out',
    mt_lbl_packets_in: 'Packets In',
    mt_lbl_packets_out: 'Packets Out',
    mt_lbl_last_login: 'Last Logged In',
    mt_lbl_on_event_script: 'On Event Script',
    mt_ex_log_message: 'Log message',
    mt_ex_remove_used_users: 'Futa used users',
    mt_ex_reboot_router: 'Reboot router',
    mt_int_every_min: 'Kila dakika',
    mt_int_every_hour: 'Kila saa',
    mt_int_every_6h: 'Kila saa 6',
    mt_int_every_day: 'Kila siku',
    mt_int_every_week: 'Kila wiki',
    th_action: 'Action',
    th_address_pool: 'Address Pool',
    th_idle_timeout: 'Idle Timeout',
    th_type: 'Type',
    th_path: 'Path',
    th_dst_host: 'Dst Host',
    th_dst_address: 'Dst Address',
    th_protocol: 'Protocol',
    mt_terminal_tab: 'Terminal',
    mt_cat_system: 'System',
    mt_cat_hotspot: 'Hotspot',
    mt_cat_network: 'Network',
    mt_cmd_clock_tz: 'Angalia Saa na Timezone',
    mt_cmd_set_tz_nairobi: 'Weka Timezone Nairobi',
    mt_cmd_sys_resources: 'System Resources',
    mt_cmd_router_identity: 'Router Identity',
    mt_cmd_routeros_version: 'RouterOS Version',
    mt_cmd_hotspot_users_count: 'Hotspot Users (idadi)',
    mt_cmd_all_schedulers: 'Schedulers Zote',
    mt_cmd_dns_settings: 'DNS Settings',
    mt_cmd_routes: 'Routes',
  },
  en: {
    login:'Login', logout:'Logout', username:'Username', password:'Password',
    logging_in:'Logging in...', welcome_back:'Welcome back', login_subtitle:'Sign in to your account',
    invalid_credentials:'Invalid username or password', account_disabled:'Account disabled',
    accounts_by_admin:'Accounts are created by the administrator only',
    dashboard:'Dashboard', clients:'Clients', routers:'Routers', packages:'Packages',
    vouchers:'Vouchers', payments:'Payments', devices:'GSM Devices', mikrotik_mgmt:'Manage MikroTik',
    summary:"Today's Summary", total_clients:'Total Clients', online_routers:'Online',
    today_revenue:"Today's Revenue", today_commission:"Today's Commission", vouchers_today:"Today's Vouchers",
    active_devices:'Active Devices', my_balance:'My Balance', pending_jobs:'Pending Jobs',
    system_status:'System Status', recent_vouchers:'Recent Vouchers',
    total_routers:'Total Routers', month_revenue:'Month Revenue', today:'Today',
    add_client:'Add Client', business_name:'Business Name', reference_prefix:'Prefix',
    commission_rate:'Commission (%)', balance:'Balance', status:'Status', active:'Active',
    inactive:'Disabled', add_balance:'Add Balance', current_balance:'Current Balance',
    amount:'Amount', save:'Save', cancel:'Cancel', create_client:'Create Client',
    auto_generated:'Auto-generated', email:'Email', phone:'Phone',
    activate:'Activate Account', deactivate:'Deactivate Account', change_password:'Change Password',
    new_password:'New Password', delete_client:'Delete Client', confirm_delete:'Confirm Delete',
    add_router:'Add Router', router_name:'Router Name', host:'Host (VPN IP)',
    api_port:'API Port', api_username:'API Username', api_password:'API Password',
    hotspot_interface:'Hotspot Interface', test_connection:'Test Connection',
    sync_packages:'Sync Packages', online:'Online', offline:'Offline', last_seen:'Last Seen',
    never:'Never', testing:'Testing...', edit_router:'Edit Router', delete_router:'Delete Router',
    vpn_hint:'Enter MikroTik VPN IP (e.g., 10.66.66.2) after connecting WireGuard',
    router_status:'Router Status', interfaces:'Interfaces', ip_addresses:'IP Addresses',
    hotspot_users:'Hotspot Users', active_sessions:'Active Sessions', hotspot_profiles:'Profiles',
    firewall:'Firewall', logs:'Logs', dns:'DNS', bandwidth:'Bandwidth',
    restart_router:'Restart Router', disconnect_session:'Disconnect',
    delete_user:'Delete User', add_user:'Add User',
    cpu_load:'CPU Load', memory:'Memory', uptime:'Uptime',
    no_sessions:'No active sessions',
    restart_confirm:'Are you sure you want to restart? All clients will be disconnected.',
    add_package:'Add Package', package_name:'Name', price:'Price (TZS)',
    duration_minutes:'Duration (minutes)', speed_down:'Download (Mbps)', speed_up:'Upload (Mbps)',
    mikrotik_profile:'MikroTik Profile', shared_users:'Shared Users', save_package:'Save',
    no_packages:'No packages yet. Add your first one!',
    code:'Code', customer_phone:'Customer Phone', all:'All', used:'Used', expired:'Expired',
    no_vouchers:'No vouchers yet',
    no_payments:'No payments yet', total_payments:'Total Payments',
    my_revenue:'My Revenue', grand_total:'Grand Total',
    add_device:'Add Device', device_name:'Device Name', device_id:'Device ID',
    phone_number:'SIM Number', description:'Description', save_device:'Save Device',
    no_devices_admin:'No devices. Add your first A7670E!',
    edit_device:'Edit Device', device_id_hint:'Must match the A7670E device_id',
    lipa_namba:'Payment Numbers', pay_instruction:'Customers enter the lipa number and your reference',
    reference:'Your Reference', lipa_number:'Lipa Number', no_devices:'No GSM devices configured',
    network:'Network',
    loading:'Loading...', no_data:'No data', error:'Error', success:'Success',
    delete:'Delete', edit:'Edit', search:'Search', from_date:'From', to_date:'To',
    actions:'Actions', super_admin:'Super Admin', client:'Client', created_at:'Created',
    app_name:'NetSafi', app_tagline:'Modern Hotspot Management Tanzania', refresh:'Refresh',
    manage:'Manage',
    zipo_online_sasa: 'Currently online',
    gsm_devices: 'GSM Devices',
    vouchers_this_week: "This Week's Vouchers",
    prefix: 'Prefix',
    commission: 'Commission',
    no_clients_yet: 'No clients yet',
    all_routers_subtitle: 'All client routers',
    all_payments_subtitle: 'All client payment history',
    all_vouchers_subtitle: 'All client vouchers',
    total_commission: 'Total Commission',
    no_routers: 'No routers',
    payment_instructions: 'Payment Instructions',
    how_customers_pay: 'How Customers Pay',
    pay_step_1: 'Customer chooses a package — each has a specific price.',
    pay_step_2: 'The price already includes your number',
    pay_step_2_suffix: '— pay the full amount without change.',
    pay_step_3_prefix: 'Example: Package TZS 500 → customer pays',
    pay_step_3_to: 'to Lipa Namba',
    pay_step_4: 'The system will send the voucher to the customer directly via SMS.',
    automatic: 'Automatic',
    your_number: 'Your Number',
    bakaa: 'Balance',
    bakaa_ya_sasa: 'Current Balance',
    by_hour: 'Per hour',
    welcome_client: 'Hello',
    business_summary_today: 'Summary of your business activities today',
    payments_today: 'Payments Today',
    vouchers_today_chart: "Today's Vouchers",
    no_vouchers_today: 'No vouchers issued today',

    // ── Voucher Management Page ──
    voucher_page_subtitle: 'Manage, create, and print vouchers',
    theme_blue: 'Blue', theme_green: 'Green', theme_purple: 'Purple', theme_red: 'Red',
    theme_orange: 'Orange', theme_teal: 'Teal', theme_black: 'Black', theme_gold: 'Gold',
    code_settings_title: 'Code Settings',
    char_type_label: 'Character Type',
    type_mixed: 'Mixed', type_letters: 'Letters Only', type_numbers: 'Numbers Only',
    char_case_label: 'Character Case',
    case_upper: 'UPPER (ABC)', case_lower: 'lower (abc)',
    char_count_label: 'Character Count',
    preview_label: 'Preview',
    tab_voucher_list: 'Voucher List', tab_voucher_manual: 'Create Single', tab_voucher_batch: 'Create Batch',
    th_package: 'Package', print: 'Print',
    print_selected_prefix: 'Print',
    deselect_all: 'Deselect All', select_all: 'Select All',
    create_manual_title: 'Create a Single Voucher',
    router_online_required: 'Router (must be online) *',
    choose_router: 'Choose Router',
    customer_phone_optional: 'Customer Phone (optional)',
    custom_code_label: 'Custom Code (leave blank = random)',
    preview_code_label: 'Preview code',
    voucher_color_label: 'Voucher Color (Print)',
    creating: 'Creating...',
    create_voucher_btn: 'Create Voucher',
    preview_voucher_label: 'Voucher Preview',
    choose_router_profile_prompt: 'Choose a router and profile',
    create_batch_title: 'Create Multiple Vouchers (Batch)',
    quantity_label: 'Number of Vouchers (1–200) *',
    vouchers_color_label: 'Vouchers Color (Print)',
    creating_on_mikrotik: 'Creating vouchers on MikroTik...',
    create_batch_btn_prefix: 'Create Vouchers',
    vouchers_created_prefix: 'Vouchers', vouchers_created_suffix: 'Created!',
    print_all: 'Print All',
    hotspot_profile_star: 'Hotspot Profile *',
    choose_router_first: 'Choose a router first...',
    loading_profiles_mikrotik: 'Loading profiles from MikroTik...',
    profiles_count_prefix: '', profiles_count_suffix: 'profiles from MikroTik',
    print_modal_title_prefix: 'Print Vouchers',
    color_label: 'Color',
    close: 'Close', print_now: 'Print Now',
    print_question: 'Would you like to print them?',
    duration_days_prefix: 'Days', duration_hours_prefix: 'Hours',
    alert_select_router_profile: 'Choose a router and profile',
    alert_voucher_created_prefix: 'Voucher', alert_voucher_created_suffix: 'created!',
    alert_create_failed: 'Failed — check that the router is online',
    alert_quantity_range: 'Quantity must be between 1 and 200',
    alert_batch_partial_ok: 'succeeded', alert_batch_partial_failed: 'failed',
    alert_batch_success_prefix: 'Vouchers', alert_batch_success_suffix: 'created!',
    alert_batch_router_failed: 'Failed to communicate with the router',

    // ── MikroTik Manager Page ──
    mt_no_permission_title: 'You do not have access to MikroTik Manager',
    mt_no_permission_title_short: 'No access to MikroTik Manager',
    mt_no_permission_contact: 'Contact your admin to get access.',
    mt_no_permission_contact_short: 'Contact admin to get access.',
    mt_terminal_banner: 'Run commands directly on your router. Commands are sent securely via the API.',
    mt_quick_commands: 'Quick Commands',
    mt_keyboard_label: 'Keyboard:',
    mt_history: 'history', mt_run_hint: 'run', mt_clear_hint: 'clear',
    mt_clear: 'Clear', mt_executing: 'Running...', mt_waiting_response: 'Waiting for response from MikroTik...',
    mt_command_placeholder: 'Type a command... (e.g. /ip/address/print)',
    mt_run_btn: 'Run',
    mt_hotspot_servers: 'Hotspot Servers', mt_no_servers: 'No hotspot servers',
    mt_server_profiles: 'Server Profiles',
    mt_profile_tip: 'Click any profile to view and edit its details (General, Scripts)',
    mt_no_profiles: 'No server profiles',
    mt_edit_profile: 'Edit Profile',
    th_name: 'Name', th_rate_limit: 'Rate Limit', th_session_timeout: 'Session Timeout',
    th_shared_users: 'Shared Users', th_on_login_script: 'On Login Script', th_status: 'Status',
    mt_ipo: 'Yes', mt_hakuna: 'None',
    mt_users_tip: 'Click a username to view and edit its details',
    mt_search_users_placeholder: 'Search by username, comment or profile...',
    mt_selected_count_suffix: 'selected',
    mt_delete_selected: 'Delete selected', mt_deselect: 'Deselect',
    mt_select_all_filtered_prefix: 'Select all', mt_deselect_all_filtered: 'Deselect all',
    mt_no_users_match_prefix: 'No user matches', mt_no_users: 'No users',
    th_profile: 'Profile', th_limit_uptime: 'Limit Uptime', th_uptime_hali: 'Uptime / Status',
    th_comment: 'Comment', th_unlimited: 'unlimited',
    mt_never_used: 'Never used', mt_login_label: 'Login', mt_last_label: 'Last', mt_nje: 'Offline',
    mt_edit_user: 'Edit User',
    mt_no_active_sessions: 'No active sessions',
    th_user: 'User', th_mac: 'MAC Address', th_ip: 'IP Address', th_tx: 'TX Bytes', th_rx: 'RX Bytes', th_server: 'Server',
    mt_disconnect: 'Disconnect',
    mt_disconnect_confirm_title: 'Disconnect Session', mt_disconnect_confirm_msg: 'Are you sure you want to disconnect this session?',
    mt_hosts_title: 'Hosts', th_hostname: 'Hostname', th_bridge: 'Bridge',
    mt_authorized: 'authorized', mt_unauthorized: 'unauthorized', mt_no_hosts: 'No hosts',
    mt_ip_bindings: 'IP Bindings', mt_add_binding: 'Add Binding', mt_no_bindings: 'No IP Bindings',
    mt_binding_regular: 'Regular — normal user', mt_binding_bypassed: 'Bypassed — allowed without login',
    mt_binding_blocked: 'Blocked — fully blocked', mt_remove_binding: 'Remove Binding',
    mt_remove_binding_title: 'Remove IP Binding', mt_remove_binding_msg: 'Are you sure you want to remove this IP Binding?',
    mt_walled_garden: 'Walled Garden', mt_add_entry: 'Add Entry',
    mt_wg_tip: 'Sites reachable without login (HTTP)', mt_no_wg: 'No Walled Garden entries',
    mt_remove_entry: 'Remove Entry', mt_remove_wg_title: 'Remove Walled Garden', mt_remove_wg_msg: 'Are you sure you want to remove this entry?',
    mt_walled_garden_ip: 'Walled Garden IP List', mt_add_ip: 'Add IP',
    mt_wgip_tip: 'IP addresses reachable without login (HTTPS/IP direct)', mt_no_wgip: 'No Walled Garden IP entries',
    mt_remove_ip: 'Remove IP', mt_remove_wgip_title: 'Remove Walled Garden IP', mt_remove_wgip_msg: 'Are you sure you want to remove this IP?',
    mt_cookies: 'Cookies', mt_clear_all: 'Clear All',
    mt_cookies_tip: 'Login cookies — let a user log in again without a password',
    mt_no_cookies: 'No cookies', mt_remove_cookie: 'Remove Cookie',
    mt_remove_cookie_title: 'Remove Cookie', mt_remove_cookie_msg: 'Remove this cookie? The user will need to log in again.',
    mt_clear_cookies_title: 'Clear All Cookies', mt_clear_cookies_msg: 'Remove ALL cookies? Every user will need to log in again.',
    th_expires_at: 'Expires At',
    mt_scheduler: 'Scheduler', mt_add_schedule: 'Add Schedule',
    mt_scheduler_tip: 'Click a scheduler to view and edit its full script', mt_no_schedulers: 'No schedulers',
    th_start_date: 'Start Date', th_start_time: 'Start Time', th_interval: 'Interval',
    th_run_count: 'Run Count', th_next_run: 'Next Run', mt_once: 'once',
    mt_edit_scheduler: 'Edit Scheduler', mt_enable: 'Enable', mt_disable: 'Disable',
    mt_delete_scheduler: 'Delete Scheduler', mt_delete_scheduler_title: 'Delete Scheduler',
    mt_delete_scheduler_msg: 'Delete this scheduler? Its script will no longer run.',
    mt_bulk_delete_title: 'Delete Selected Users',
    mt_bulk_delete_msg_prefix: 'Are you sure you want to delete', mt_bulk_delete_msg_suffix: 'user(s)? This action cannot be undone!',
    mt_deleting: 'Deleting...',
    mt_add_user_title: 'Add User', mt_username_star: 'Username *', mt_password_default: 'Password (default = username)',
    mt_leave_blank: 'Leave blank', mt_profile_label: 'Profile', mt_loading_short: 'Loading...',
    mt_comment_optional: 'Comment (optional)', mt_customer_name_hint: "Customer's name",
    mt_add_binding_title: 'Add IP Binding', mt_mac_star: 'MAC Address *', mt_ip_optional: 'IP Address (optional)',
    mt_type_label: 'Type', mt_notes_hint: 'Notes',
    mt_add_wg_title: 'Add Walled Garden Entry', mt_dst_host_star: 'Dst Host *',
    mt_action_label: 'Action', mt_allow_desc: 'Allow — permit without login', mt_deny_desc: 'Deny — block',
    mt_add_wgip_title: 'Add Walled Garden IP', mt_dst_address_star: 'Dst Address *',
    mt_accept_desc: 'Accept — permit', mt_drop_desc: 'Drop — block',
    mt_add_scheduler_title: 'Add Scheduler', mt_edit_scheduler_prefix: 'Edit',
    mt_scheduler_name_star: 'Name *', mt_start_date_hint: 'Format: jan/01/1970', mt_start_time_hint: 'Format: HH:MM:SS',
    mt_interval_hint: 'Interval (00:00:00 = run once only)',
    mt_policy_label: 'Policy', mt_on_event_star: 'On Event (Script) *',
    mt_examples_label: 'Examples:', mt_examples_label_full: 'Quick examples:',
    mt_scheduler_comment_hint: 'Scheduler notes', mt_initial_status: 'Initial Status',
    mt_update_btn: 'Update', mt_add_scheduler_btn: 'Add Scheduler',
    mt_live_label: 'Live',
    mt_permissions_title: 'MikroTik Permissions', mt_select_all_features: 'Select All', mt_clear_all_features: 'Clear All',
    mt_features_selected_suffix: 'features selected', mt_saving: 'Saving...',
    mt_save_failed: 'Failed to save permissions',
    mt_mikrotik_by_client_subtitle: 'IP → Hotspot (like Winbox)',
    mt_mikrotik_by_admin_subtitle: 'Manage all client routers',
    mt_back: 'Back', mt_no_routers_short: 'No routers',
    mt_feature_desc_servers: 'View hotspot servers', mt_feature_desc_server_profiles: 'View server profiles',
    mt_feature_desc_users: 'Manage hotspot users', mt_feature_desc_active: 'View and disconnect sessions',
    mt_feature_desc_hosts: 'Connected devices', mt_feature_desc_ip_bindings: 'Manage IP bindings',
    mt_feature_desc_walled_garden: 'Sites without login (HTTP)', mt_feature_desc_walled_garden_ip: 'IPs without login (HTTPS)',
    mt_feature_desc_cookies: 'Manage login cookies', mt_feature_desc_scheduler: 'Scheduled scripts',
    mt_feature_desc_terminal: 'Run commands directly',
    mt_funga: 'Close', mt_hifadhi: 'Save',

    // ── Generic UI (confirm dialogs, forms, save states) ──
    confirm: 'Confirm',
    saving_label: 'Saving...',
    fill_required: 'Please fill in all required fields',
    updated_success: 'updated successfully',
    created_success: 'created successfully',
    deleted_success: 'deleted successfully',

    // ── Client Packages page ──
    manage_packages_subtitle: 'Manage your internet packages',
    sync_all: 'Sync All',
    sync: 'Sync',
    sync_all_success: 'All packages synced to MikroTik',
    sync_failed: 'Sync failed',
    customers: 'Customers',
    customers_pay: 'Customers will pay',
    base_price_note: 'The price shown on the card is the base price.',
    customers_will_pay: 'Your customers will pay',
    example_label: 'Example',
    duration_of_package: 'Package Duration',
    hours_unit: 'Hours',
    days_unit: 'Days',
    minutes_unit: 'minutes',
    confirm_delete_package_prefix: 'Delete package',

    // ── Withdraw / Withdrawal Requests ──
    withdraw: 'Withdraw',
    withdraw_page_subtitle: 'Request to withdraw funds from your balance',
    request_withdrawal: 'Request Withdrawal',
    account_name: 'Account Holder Name',
    withdrawal_history: 'Request History',
    no_withdrawals: 'No requests yet',
    withdrawal_requested_success: 'Your request has been sent — awaiting admin approval',
    withdrawal_requests: 'Withdrawal Requests',
    withdrawal_requests_subtitle: "Manage clients' withdrawal requests",
    approve: 'Approve',
    reject: 'Reject',
    pending_status: 'Pending',
    approved_status: 'Approved',
    rejected_status: 'Rejected',
    approve_withdrawal_title: 'Approve Withdrawal Request',
    approve_withdrawal_message_prefix: 'Are you sure you want to approve the request from',
    reject_withdrawal_title: 'Reject Withdrawal Request',
    reject_reason_prompt: 'Reason for rejection (optional)',
    reject_reason_placeholder: 'e.g. Incorrect lipa number',
    withdrawal_approved_success: 'Request approved and balance deducted',
    withdrawal_rejected_success: 'Request rejected',

    // ── MikroTik Manager — small set of keys missing for full coverage ──
    view: 'View',
    mt_view_tooltip: 'View only',
    mt_edit_tooltip: 'Edit',
    mt_tab_general: 'General',
    mt_tab_scripts: 'Scripts',
    mt_tab_script: 'Script',
    mt_tab_statistics: 'Statistics',
    mt_profile_modal_title: 'Hotspot User Profile',
    mt_user_modal_title: 'Hotspot User',
    mt_cannot_change: 'cannot be changed',
    mt_hidden: 'hidden',
    mt_yes: 'Yes',
    mt_no: 'No',
    mt_ok: 'OK',
    mt_apply: 'Apply',
    mt_on_login: 'On Login',
    mt_on_logout: 'On Logout',
    mt_no_script: 'No script',
    mt_no_stats: 'No statistics — user has never logged in',
    mt_no_results: 'no results',
    mt_empty_list: 'empty list',
    mt_command_failed: 'Command failed',
    mt_connection_error: 'Connection error',
    mt_results_label: 'Results',
    mt_items_label: 'item(s)',
    mt_term_ready: 'MikroTik Terminal — ready to use',
    mt_term_intro: 'Use quick commands or type your own command below.',
    mt_terminal_cleared: 'Terminal cleared.',
    mt_terminal_cleared_ready: 'Terminal cleared. Ready to use.',
    mt_clear_screen_tooltip: 'Clear terminal screen',
    mt_save_generic_failed: 'Failed to save',
    mt_session_disconnected: 'Session disconnected',
    mt_action_irreversible: 'This action cannot be undone!',
    mt_confirm_delete_user_msg_prefix: 'Delete user',
    mt_bulk_failed_note: ', failed to delete',
    mt_any: 'any',
    mt_ph_new_password: 'Enter new password',
    mt_ph_bytes_unlimited: 'bytes (0 = unlimited)',
    mt_opt_active_desc: 'Active — user can log in',
    mt_opt_disabled_desc: 'Disabled — user is blocked',
    mt_opt_enabled_desc: 'Enabled — active',
    mt_opt_disabled_desc2: 'Disabled — stopped',
    mt_lbl_idle_timeout: 'Idle Timeout',
    mt_lbl_keepalive_timeout: 'Keepalive Timeout',
    mt_lbl_dns_name: 'DNS Name',
    mt_lbl_html_directory: 'HTML Directory',
    mt_lbl_http_cookie_lifetime: 'HTTP Cookie Lifetime',
    mt_lbl_status_autorefresh: 'Status Auto-Refresh',
    mt_lbl_address_pool: 'Address Pool',
    mt_lbl_mac_cookie_timeout: 'MAC Cookie Timeout',
    mt_lbl_transparent_proxy: 'Transparent Proxy',
    mt_lbl_limit_bytes_in: 'Limit Bytes In',
    mt_lbl_limit_bytes_out: 'Limit Bytes Out',
    mt_lbl_limit_bytes_total: 'Limit Bytes Total',
    mt_lbl_disabled_field: 'Disabled',
    mt_lbl_bytes_in: 'Bytes In',
    mt_lbl_bytes_out: 'Bytes Out',
    mt_lbl_packets_in: 'Packets In',
    mt_lbl_packets_out: 'Packets Out',
    mt_lbl_last_login: 'Last Logged In',
    mt_lbl_on_event_script: 'On Event Script',
    mt_ex_log_message: 'Log message',
    mt_ex_remove_used_users: 'Remove used users',
    mt_ex_reboot_router: 'Reboot router',
    mt_int_every_min: 'Every minute',
    mt_int_every_hour: 'Every hour',
    mt_int_every_6h: 'Every 6 hours',
    mt_int_every_day: 'Every day',
    mt_int_every_week: 'Every week',
    th_action: 'Action',
    th_address_pool: 'Address Pool',
    th_idle_timeout: 'Idle Timeout',
    th_type: 'Type',
    th_path: 'Path',
    th_dst_host: 'Dst Host',
    th_dst_address: 'Dst Address',
    th_protocol: 'Protocol',
    mt_terminal_tab: 'Terminal',
    mt_cat_system: 'System',
    mt_cat_hotspot: 'Hotspot',
    mt_cat_network: 'Network',
    mt_cmd_clock_tz: 'Check Clock & Timezone',
    mt_cmd_set_tz_nairobi: 'Set Timezone to Nairobi',
    mt_cmd_sys_resources: 'System Resources',
    mt_cmd_router_identity: 'Router Identity',
    mt_cmd_routeros_version: 'RouterOS Version',
    mt_cmd_hotspot_users_count: 'Hotspot Users (count)',
    mt_cmd_all_schedulers: 'All Schedulers',
    mt_cmd_dns_settings: 'DNS Settings',
    mt_cmd_routes: 'Routes',
  }
}

interface LangCtx { lang: Language; setLang:(l:Language)=>void; t:(key:string)=>string }
const LangContext = createContext<LangCtx|null>(null)

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => (localStorage.getItem('ns_lang') as Language) || 'sw')
  const setLang = (l: Language) => { setLangState(l); localStorage.setItem('ns_lang', l) }
  const t = (key: string): string => T[lang][key] || T['sw'][key] || key
  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>
}

export const useLang = () => { const ctx = useContext(LangContext); if (!ctx) throw new Error('useLang'); return ctx }

// ── Real SVG globe icon (no emoji flags) ──────────────────
const GlobeIcon = ({ size = 13 }: { size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="12" r="10" />
    <line x1="2" y1="12" x2="22" y2="12" />
    <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
  </svg>
)

// ── Language switcher: sliding pill, real icon, smooth animation ──
export function LanguageSwitcher({ dark = true }: { dark?: boolean }) {
  const { lang, setLang } = useLang()
  const options: { key: Language; label: string }[] = [
    { key: 'sw', label: 'SW' },
    { key: 'en', label: 'EN' },
  ]
  const activeIndex = lang === 'sw' ? 0 : 1

  const trackBg = dark ? 'rgba(255,255,255,0.14)' : 'var(--gray-100)'
  const trackBorder = dark ? '1px solid rgba(255,255,255,0.22)' : '1px solid var(--gray-200)'
  const inactiveColor = dark ? 'rgba(255,255,255,0.75)' : 'var(--gray-500)'
  const activeColor = '#fff'
  const pillBg = dark
    ? 'linear-gradient(135deg,#6366f1 0%,#4f46e5 100%)'
    : 'linear-gradient(135deg,var(--primary) 0%,#4f46e5 100%)'

  return (
    <div
      role="group"
      aria-label="Language switcher"
      style={{
        position: 'relative',
        display: 'inline-flex',
        alignItems: 'center',
        gap: 5,
        background: trackBg,
        border: trackBorder,
        borderRadius: 10,
        padding: 3,
        width: 118,
        height: 32,
        boxSizing: 'border-box',
        overflow: 'hidden',
        boxShadow: dark ? 'inset 0 1px 3px rgba(0,0,0,0.25)' : 'inset 0 1px 2px rgba(0,0,0,0.04)',
      }}
    >
      {/* Sliding active pill */}
      <div
        style={{
          position: 'absolute',
          top: 3,
          left: 3,
          width: 'calc(50% - 3px)',
          height: 'calc(100% - 6px)',
          borderRadius: 7,
          background: pillBg,
          boxShadow: '0 2px 8px rgba(99,102,241,0.4)',
          transform: `translateX(${activeIndex * 100}%)`,
          transition: 'transform 0.25s cubic-bezier(0.34,1.4,0.64,1)',
          pointerEvents: 'none',
        }}
      />
      {options.map((opt, i) => {
        const isActive = lang === opt.key
        return (
          <button
            key={opt.key}
            onClick={() => setLang(opt.key)}
            aria-pressed={isActive}
            style={{
              position: 'relative',
              zIndex: 1,
              flex: 1,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 4,
              height: '100%',
              border: 'none',
              background: 'transparent',
              borderRadius: 7,
              fontSize: 12,
              fontWeight: 700,
              letterSpacing: '0.02em',
              cursor: 'pointer',
              color: isActive ? activeColor : inactiveColor,
              transition: 'color 0.2s ease',
            }}
          >
            {i === 0 && <GlobeIcon size={12} />}
            {opt.label}
          </button>
        )
      })}
    </div>
  )
}
